version: '3'

services:

  myimage1:
    build: ./peko
    container_name: myimage1
    ports:
      - 8081:80
    expose:
      - 8081
  
  myimage2:
    build: ./welcome
    container_name: myimage2
    ports:
      - 8082:80
    expose:
      - 8082